# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/client
import wayland/native/common
import code
export code

## The river_window_management_v1 CLIENT protocol
## ##############################################
## 
## Interfaces
## ==========
## 
## * river_window_manager_v1
## * river_window_v1
## * river_decoration_v1
## * river_shell_surface_v1
## * river_node_v1
## * river_output_v1
## * river_seat_v1
## * river_pointer_binding_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2024 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverWindowManagerV1Listener* = object
  unavailable*:
    proc(data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1) {.nimcall.}
  finished*:
    proc(data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1) {.nimcall.}
  manageStart*:
    proc(data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1) {.nimcall.}
  renderStart*:
    proc(data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1) {.nimcall.}
  sessionLocked*:
    proc(data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1) {.nimcall.}
  sessionUnlocked*:
    proc(data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1) {.nimcall.}
  window*: proc(
    data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1, id: ptr RiverWindowV1
  ) {.nimcall.}
  output*: proc(
    data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1, id: ptr RiverOutputV1
  ) {.nimcall.}
  seat*: proc(
    data: pointer, riverWindowManagerV1: ptr RiverWindowManagerV1, id: ptr RiverSeatV1
  ) {.nimcall.}

proc addListener*(
    riverWindowManagerV1: ptr RiverWindowManagerV1,
    listener: ptr RiverWindowManagerV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](riverWindowManagerV1).add_listener(listener, data)

proc setUserData*(
    riverWindowManagerV1: ptr RiverWindowManagerV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](riverWindowManagerV1).set_user_data(user_data)

proc getUserData*(riverWindowManagerV1: ptr RiverWindowManagerV1): pointer {.inline.} =
  cast[ptr Proxy](riverWindowManagerV1).get_user_data()

proc getVersion*(riverWindowManagerV1: ptr RiverWindowManagerV1): uint32 {.inline.} =
  cast[ptr Proxy](riverWindowManagerV1).get_version()

proc stop*(riverWindowManagerV1: ptr RiverWindowManagerV1) {.inline.} =
  ## stop sending events
  ##
  ## This request indicates that the client no longer wishes to receive
  ## events on this object.
  ##
  ## The Wayland protocol is asynchronous, which means the server may send
  ## further events until the stop request is processed. The client must wait
  ## for a river_window_manager_v1.finished event before destroying this
  ## object.
  ##
  cast[ptr Proxy](riverWindowManagerV1).marshal_flags(
    RiverWindowManagerV1Request_stop.ord,
    nil,
    cast[ptr Proxy](riverWindowManagerV1).get_version(),
    0,
  )

proc destroy*(riverWindowManagerV1: ptr RiverWindowManagerV1) {.inline.} =
  ## destroy the river_window_manager_v1 object
  ##
  ## This request should be called after the finished event has been received
  ## to complete destruction of the object.
  ## 
  ## If a client wishes to destroy this object it should send a
  ## river_window_manager_v1.stop request and wait for a
  ## river_window_manager_v1.finished event. Once the finished event is
  ## received it is safe to destroy this object and any other objects created
  ## through this interface.
  ## 
  cast[ptr Proxy](riverWindowManagerV1).marshal_flags(
    RiverWindowManagerV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverWindowManagerV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc manageFinish*(riverWindowManagerV1: ptr RiverWindowManagerV1) {.inline.} =
  ## finish a manage sequence
  ## 
  ## This request indicates that the client has made all changes to window
  ## management state it wishes to include in the current manage sequence and
  ## that the server should atomically send these state changes to the
  ## windows and continue with the manage sequence.
  ## 
  ## After sending this request, it is a protocol error for the client to
  ## make further changes to window management state until the next
  ## manage_start event is received.
  ## 
  ## See the description of the river_window_manager_v1 interface for a
  ## complete overview of the manage/render sequence loop.
  ## 
  cast[ptr Proxy](riverWindowManagerV1).marshal_flags(
    RiverWindowManagerV1Request_manage_finish.ord,
    nil,
    cast[ptr Proxy](riverWindowManagerV1).get_version(),
    0,
  )

proc manageDirty*(riverWindowManagerV1: ptr RiverWindowManagerV1) {.inline.} =
  ## ensure a manage sequence is started
  ## 
  ## This request ensures a manage sequence is started and that a
  ## manage_start event is sent by the server. If this request is made during
  ## an ongoing manage sequence, a new manage sequence will be started as
  ## soon as the current one is completed.
  ## 
  ## The client may want to use this request due to an internal state change
  ## that the compositor is not aware of (e.g. a dbus event) which should
  ## affect window management or rendering state.
  ## 
  cast[ptr Proxy](riverWindowManagerV1).marshal_flags(
    RiverWindowManagerV1Request_manage_dirty.ord,
    nil,
    cast[ptr Proxy](riverWindowManagerV1).get_version(),
    0,
  )

proc renderFinish*(riverWindowManagerV1: ptr RiverWindowManagerV1) {.inline.} =
  ## finish a render sequence
  ## 
  ## This request indicates that the client has made all changes to rendering
  ## state it wishes to include in the current manage sequence and that the
  ## server should atomically apply and display these state changes to the
  ## user.
  ## 
  ## After sending this request, it is a protocol error for the client to
  ## make further changes to rendering state until the next manage_start or
  ## render_start event is received, whichever comes first.
  ## 
  ## See the description of the river_window_manager_v1 interface for a
  ## complete overview of the manage/render sequence loop.
  ## 
  cast[ptr Proxy](riverWindowManagerV1).marshal_flags(
    RiverWindowManagerV1Request_render_finish.ord,
    nil,
    cast[ptr Proxy](riverWindowManagerV1).get_version(),
    0,
  )

proc getShellSurface*(
    riverWindowManagerV1: ptr RiverWindowManagerV1, surface: ptr Surface
): ptr RiverShellSurfaceV1 {.inline.} =
  ## assign the river_shell_surface_v1 surface role
  ## 
  ## Create a new shell surface for window manager UI and assign the
  ## river_shell_surface_v1 role to the surface.
  ## 
  ## Providing a wl_surface which already has a role or already has a buffer
  ## attached or committed is a protocol error.
  ## 
  cast[ptr RiverShellSurfaceV1](cast[ptr Proxy](riverWindowManagerV1).marshal_flags(
    RiverWindowManagerV1Request_get_shell_surface.ord,
    addr river_shell_surface_v1_interface,
    cast[ptr Proxy](riverWindowManagerV1).get_version(),
    0,
    nil,
    surface,
  ))

proc exitSession*(riverWindowManagerV1: ptr RiverWindowManagerV1) {.inline.} =
  ## exit the Wayland session
  ## 
  ## End the current Wayland session and exit the compositor.
  ## All Wayland clients running in the current session, including
  ## the window manager, will be disconnected.
  ## 
  ## Window managers should only make this request if the user explicitly
  ## asks to exit the Wayland session, not for example on normal window
  ## manager termination.
  ## 
  cast[ptr Proxy](riverWindowManagerV1).marshal_flags(
    RiverWindowManagerV1Request_exit_session.ord,
    nil,
    cast[ptr Proxy](riverWindowManagerV1).get_version(),
    0,
  )

type RiverWindowV1Listener* = object
  closed*: proc(data: pointer, riverWindowV1: ptr RiverWindowV1) {.nimcall.}
  dimensionsHint*: proc(
    data: pointer,
    riverWindowV1: ptr RiverWindowV1,
    minWidth: int32,
    minHeight: int32,
    maxWidth: int32,
    maxHeight: int32,
  ) {.nimcall.}
  dimensions*: proc(
    data: pointer, riverWindowV1: ptr RiverWindowV1, width: int32, height: int32
  ) {.nimcall.}
  appId*:
    proc(data: pointer, riverWindowV1: ptr RiverWindowV1, appId: cstring) {.nimcall.}
  title*:
    proc(data: pointer, riverWindowV1: ptr RiverWindowV1, title: cstring) {.nimcall.}
  parent*: proc(
    data: pointer, riverWindowV1: ptr RiverWindowV1, parent: ptr RiverWindowV1
  ) {.nimcall.}
  decorationHint*:
    proc(data: pointer, riverWindowV1: ptr RiverWindowV1, hint: uint32) {.nimcall.}
  pointerMoveRequested*: proc(
    data: pointer, riverWindowV1: ptr RiverWindowV1, seat: ptr RiverSeatV1
  ) {.nimcall.}
  pointerResizeRequested*: proc(
    data: pointer,
    riverWindowV1: ptr RiverWindowV1,
    seat: ptr RiverSeatV1,
    edges: uint32,
  ) {.nimcall.}
  showWindowMenuRequested*: proc(
    data: pointer, riverWindowV1: ptr RiverWindowV1, x: int32, y: int32
  ) {.nimcall.}
  maximizeRequested*: proc(data: pointer, riverWindowV1: ptr RiverWindowV1) {.nimcall.}
  unmaximizeRequested*:
    proc(data: pointer, riverWindowV1: ptr RiverWindowV1) {.nimcall.}
  fullscreenRequested*: proc(
    data: pointer, riverWindowV1: ptr RiverWindowV1, output: ptr RiverOutputV1
  ) {.nimcall.}
  exitFullscreenRequested*:
    proc(data: pointer, riverWindowV1: ptr RiverWindowV1) {.nimcall.}
  minimizeRequested*: proc(data: pointer, riverWindowV1: ptr RiverWindowV1) {.nimcall.}
  unreliablePid*: proc(
    data: pointer, riverWindowV1: ptr RiverWindowV1, unreliablePid: int32
  ) {.nimcall.}
  presentationHint*:
    proc(data: pointer, riverWindowV1: ptr RiverWindowV1, hint: uint32) {.nimcall.}
  identifier*: proc(
    data: pointer, riverWindowV1: ptr RiverWindowV1, identifier: cstring
  ) {.nimcall.}
  captureSessions*:
    proc(data: pointer, riverWindowV1: ptr RiverWindowV1, count: uint32) {.nimcall.}

proc addListener*(
    riverWindowV1: ptr RiverWindowV1, listener: ptr RiverWindowV1Listener, data: pointer
): int {.inline.} =
  cast[ptr Proxy](riverWindowV1).add_listener(listener, data)

proc setUserData*(riverWindowV1: ptr RiverWindowV1, userData: pointer) {.inline.} =
  cast[ptr Proxy](riverWindowV1).set_user_data(user_data)

proc getUserData*(riverWindowV1: ptr RiverWindowV1): pointer {.inline.} =
  cast[ptr Proxy](riverWindowV1).get_user_data()

proc getVersion*(riverWindowV1: ptr RiverWindowV1): uint32 {.inline.} =
  cast[ptr Proxy](riverWindowV1).get_version()

proc destroy*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## destroy the window object
  ## 
  ## This request indicates that the client will no longer use the window
  ## object and that it may be safely destroyed.
  ## 
  ## This request should be made after the river_window_v1.closed event or
  ## river_window_manager_v1.finished is received to complete destruction of
  ## the window.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc close*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## request that the window be closed
  ## 
  ## Request that the window be closed. The window may ignore this request or
  ## only close after some delay, perhaps opening a dialog asking the user to
  ## save their work or similar.
  ## 
  ## The server will send a river_window_v1.closed event if/when the window
  ## has been closed.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_close.ord, nil, cast[ptr Proxy](riverWindowV1).get_version(), 0
  )

proc getNode*(riverWindowV1: ptr RiverWindowV1): ptr RiverNodeV1 {.inline.} =
  ## get the window's render list node
  ## 
  ## Get the node in the render list corresponding to the window.
  ## 
  ## It is a protocol error to make this request more than once for a single
  ## window.
  ## 
  cast[ptr RiverNodeV1](cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_get_node.ord,
    addr river_node_v1_interface,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    nil,
  ))

proc proposeDimensions*(
    riverWindowV1: ptr RiverWindowV1, width: int32, height: int32
) {.inline.} =
  ## propose window dimensions
  ## 
  ## This request proposes dimensions for the window in the compositor's
  ## logical coordinate space.
  ## 
  ## The width and height must be greater than or equal to zero. If the width
  ## or height is zero the window will be allowed to decide its own
  ## dimensions.
  ## 
  ## The window may not take the exact dimensions proposed. The actual
  ## dimensions taken by the window will be sent in a subsequent
  ## river_window_v1.dimensions event. For example, a terminal emulator may
  ## only allow dimensions that are multiple of the cell size.
  ## 
  ## When a propose_dimensions request is made, the server must send a
  ## dimensions event in response as soon as possible. It may not be possible
  ## to send a dimensions event in the very next render sequence if, for
  ## example, the window takes too long to respond to the proposed
  ## dimensions. In this case, the server will send the dimensions event in a
  ## future render sequence.
  ## 
  ## Note that the dimensions of a river_window_v1 refer to the dimensions of
  ## the window content and are unaffected by the presence of borders or
  ## decoration surfaces.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_propose_dimensions.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    width,
    height,
  )

proc hide*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## request that the window be hidden
  ## 
  ## Request that the window be hidden. Has no effect if the window is
  ## already hidden. Hides any window borders and decorations as well.
  ## 
  ## Newly created windows are considered shown unless explicitly hidden with
  ## the hide request.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_hide.ord, nil, cast[ptr Proxy](riverWindowV1).get_version(), 0
  )

proc show*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## request that the window be shown
  ## 
  ## Request that the window be shown. Has no effect if the window is not
  ## hidden. Does not guarantee that the window is visible as it may be
  ## completely obscured by other windows placed above it for example.
  ## 
  ## Newly created windows are considered shown unless explicitly hidden with
  ## the hide request.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_show.ord, nil, cast[ptr Proxy](riverWindowV1).get_version(), 0
  )

proc useCsd*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## tell the client to use CSD
  ## 
  ## Tell the client to use client side decoration and draw its own title
  ## bar, borders, etc.
  ## 
  ## This is the default if neither this request nor the use_ssd request is
  ## ever made.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_use_csd.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc useSsd*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## tell the client to use SSD
  ## 
  ## Tell the client to use server side decoration and not draw any client
  ## side decorations.
  ## 
  ## This request will have no effect if the client only supports client side
  ## decoration, see the decoration_hint event.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_use_ssd.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc setBorders*(
    riverWindowV1: ptr RiverWindowV1,
    edges: uint32,
    width: int32,
    r: uint32,
    g: uint32,
    b: uint32,
    a: uint32,
) {.inline.} =
  ## set window borders
  ## 
  ## This request decorates the window with borders drawn by the compositor
  ## on the specified edges of the window. Borders are drawn above the window
  ## content.
  ## 
  ## Corners are drawn only between borders on adjacent edges. If e.g. the
  ## left edge has a border and the top edge does not, the border drawn on
  ## the left edge will not extend vertically beyond the top edge of the
  ## window.
  ## 
  ## Borders are not drawn while the window is fullscreen.
  ## 
  ## The color is defined by four 32-bit RGBA values. Unless specified in
  ## another protocol extension, the RGBA values use pre-multiplied alpha.
  ## 
  ## The valid range for the RGBA values is from 0x00000000 to 0xffffffff.
  ## These values are interpreted as a percentage:
  ## - 0x00000000 means 0% of the given color component
  ## - 0xffffffff means 100% of the given color component
  ## 
  ## Setting the edges to none or the width to 0 disables the borders.
  ## Setting a negative width is a protocol error.
  ## 
  ## This request completely overrides all previous set_borders requests.
  ## Only the most recent set_borders request has an effect.
  ## 
  ## Note that the position/dimensions of a river_window_v1 refer to the
  ## position/dimensions of the window content and are unaffected by the
  ## presence of borders or decoration surfaces.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_set_borders.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    edges,
    width,
    r,
    g,
    b,
    a,
  )

proc setTiled*(riverWindowV1: ptr RiverWindowV1, edges: uint32) {.inline.} =
  ## set window tiled state
  ## 
  ## Inform the window that it is part of a tiled layout and adjacent to
  ## other elements in the tiled layout on the given edges.
  ## 
  ## The window should use this information to change the style of its client
  ## side decorations and avoid drawing e.g. drop shadows outside of the
  ## window dimensions on the tiled edges.
  ## 
  ## Setting the edges argument to none informs the window that it is not
  ## part of a tiled layout. If this request is never made, the window is
  ## informed that it is not part of a tiled layout.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_set_tiled.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    edges,
  )

proc getDecorationAbove*(
    riverWindowV1: ptr RiverWindowV1, surface: ptr Surface
): ptr RiverDecorationV1 {.inline.} =
  ## create a decoration above the window in z-order
  ## 
  ## Create a decoration surface and assign the river_decoration_v1 role to
  ## the surface. The created decoration is placed above the window in
  ## rendering order, see the description of river_decoration_v1.
  ## 
  ## Providing a wl_surface which already has a role or already has a buffer
  ## attached or committed is a protocol error.
  ## 
  cast[ptr RiverDecorationV1](cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_get_decoration_above.ord,
    addr river_decoration_v1_interface,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    nil,
    surface,
  ))

proc getDecorationBelow*(
    riverWindowV1: ptr RiverWindowV1, surface: ptr Surface
): ptr RiverDecorationV1 {.inline.} =
  ## create a decoration below the window in z-order
  ## 
  ## Create a decoration surface and assign the river_decoration_v1 role to
  ## the surface. The created decoration is placed below the window in
  ## rendering order, see the description of river_decoration_v1.
  ## 
  ## Providing a wl_surface which already has a role or already has a buffer
  ## attached or committed is a protocol error.
  ## 
  cast[ptr RiverDecorationV1](cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_get_decoration_below.ord,
    addr river_decoration_v1_interface,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    nil,
    surface,
  ))

proc informResizeStart*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## inform the window it is being resized
  ## 
  ## Inform the window that it is being resized. The window manager should
  ## use this request to inform windows that are the target of an interactive
  ## resize for example.
  ## 
  ## The window manager remains responsible for handling the position and
  ## dimensions of the window while it is resizing.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_inform_resize_start.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc informResizeEnd*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## inform the window it no longer being resized
  ## 
  ## Inform the window that it is no longer being resized. The window manager
  ## should use this request to inform windows that are the target of an
  ## interactive resize that the interactive resize has ended for example.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_inform_resize_end.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc setCapabilities*(riverWindowV1: ptr RiverWindowV1, caps: uint32) {.inline.} =
  ## inform window of supported capabilities
  ## 
  ## This request informs the window of the capabilities supported by the
  ## window manager. If the window manager, for example, ignores requests to
  ## be maximized from the window it should not tell the window that it
  ## supports the maximize capability.
  ## 
  ## The window might use this information to, for example, only show a
  ## maximize button if the window manager supports the maximize capability.
  ## 
  ## The window manager client should use this request to set capabilities
  ## for all new windows. If this request is never made, the compositor will
  ## inform windows that all capabilities are supported.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_set_capabilities.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    caps,
  )

proc informMaximized*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## inform the window that it is maximized
  ## 
  ## Inform the window that it is maximized. The window might use this
  ## information to adapt the style of its client-side window decorations for
  ## example.
  ## 
  ## The window manager remains responsible for handling the position and
  ## dimensions of the window while it is maximized.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_inform_maximized.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc informUnmaximized*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## inform the window that it is unmaximized
  ## 
  ## Inform the window that it is unmaximized. The window might use this
  ## information to adapt the style of its client-side window decorations for
  ## example.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_inform_unmaximized.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc informFullscreen*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## inform the window that it is fullscreen
  ## 
  ## Inform the window that it is fullscreen. The window might use this
  ## information to adapt the style of its client-side window decorations for
  ## example.
  ## 
  ## This request does not affect the size/position of the window or cause it
  ## to become the only window rendered, see the river_window_v1.fullscreen
  ## and exit_fullscreen requests for that.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_inform_fullscreen.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc informNotFullscreen*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## inform the window that it is not fullscreen
  ## 
  ## Inform the window that it is not fullscreen. The window might use this
  ## information to adapt the style of its client-side window decorations for
  ## example.
  ## 
  ## This request does not affect the size/position of the window or cause it
  ## to become the only window rendered, see the river_window_v1.fullscreen
  ## and exit_fullscreen requests for that.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_inform_not_fullscreen.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc fullscreen*(
    riverWindowV1: ptr RiverWindowV1, output: ptr RiverOutputV1
) {.inline.} =
  ## make the window fullscreen
  ## 
  ## Make the window fullscreen on the given output. If multiple windows are
  ## fullscreen on the same output at the same time only the "top" window in
  ## rendering order shall be displayed.
  ## 
  ## All river_shell_surface_v1 objects above the top fullscreen window in
  ## the rendering order will continue to be rendered.
  ## 
  ## The compositor will handle the position and dimensions of the window
  ## while it is fullscreen. The set_position and propose_dimensions requests
  ## shall not affect the current position and dimensions of a fullscreen
  ## window.
  ## 
  ## When a fullscreen request is made, the server must send a dimensions
  ## event in response as soon as possible. It may not be possible to send a
  ## dimensions event in the very next render sequence if, for example, the
  ## window takes too long to respond. In this case, the server will send the
  ## dimensions event in a future render sequence.
  ## 
  ## The compositor will clip window content, decoration surfaces, and
  ## borders to the given output's dimensions while the window is fullscreen.
  ## The effects of set_clip_box and set_content_clip_box are ignored while
  ## the window is fullscreen.
  ## 
  ## If the output on which a window is currently fullscreen is removed, the
  ## windowing state is modified as if there were an exit_fullscreen request
  ## made in the same manage sequence as the river_output_v1.removed event.
  ## 
  ## This request does not inform the window that it is fullscreen, see the
  ## river_window_v1.inform_fullscreen and inform_not_fullscreen requests.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_fullscreen.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    output,
  )

proc exitFullscreen*(riverWindowV1: ptr RiverWindowV1) {.inline.} =
  ## make the window not fullscreen
  ## 
  ## Make the window not fullscreen.
  ## 
  ## The position and dimensions are undefined after this request is made
  ## until a manage sequence in which the window manager makes the
  ## propose_dimensions and set_position requests is completed.
  ## 
  ## The window manager should make propose_dimensions and set_position
  ## requests in the same manage sequence as the exit_fullscreen request for
  ## frame perfection.
  ## 
  ## This request does not inform the window that it is fullscreen, see the
  ## river_window_v1.inform_fullscreen and inform_not_fullscreen requests.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_exit_fullscreen.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
  )

proc setClipBox*(
    riverWindowV1: ptr RiverWindowV1, x: int32, y: int32, width: int32, height: int32
) {.inline.} =
  ## clip the window to a given box
  ## 
  ## Clip the window, including borders and decoration surfaces, to the box
  ## specified by the x, y, width, and height arguments. The x/y position of
  ## the box is relative to the top left corner of the window.
  ## 
  ## The width and height arguments must be greater than or equal to 0.
  ## 
  ## Setting a clip box with 0 width or height disables clipping.
  ## 
  ## The clip box is ignored while the window is fullscreen.
  ## 
  ## Both set_clip_box and set_content_clip_box may be enabled simultaneously.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_set_clip_box.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    x,
    y,
    width,
    height,
  )

proc setContentClipBox*(
    riverWindowV1: ptr RiverWindowV1, x: int32, y: int32, width: int32, height: int32
) {.inline.} =
  ## clip the window content to a given box
  ## 
  ## Clip the content of the window, excluding borders and decoration
  ## surfaces, to the box specified by the x, y, width, and height arguments.
  ## The x/y position of the box is relative to the top left corner of the
  ## window.
  ## 
  ## Borders drawn by the compositor (see set_borders) are placed around the
  ## intersection of the window content (as defined by the dimensions event)
  ## and the content clip box when content clipping is enabled.
  ## 
  ## The width and height arguments must be greater than or equal to 0.
  ## 
  ## Setting a box with 0 width or height disables content clipping.
  ## 
  ## The content clip box is ignored while the window is fullscreen.
  ## 
  ## Both set_clip_box and set_content_clip_box may be enabled simultaneously.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_set_content_clip_box.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    x,
    y,
    width,
    height,
  )

proc setDimensionBounds*(
    riverWindowV1: ptr RiverWindowV1, maxWidth: int32, maxHeight: int32
) {.inline.} =
  ## recommend maximum dimensions to the window
  ## 
  ## Recommend that the window keep its dimensions within a given
  ## maximum width/height. This recommendation is only a hint and the window
  ## may ignore it.
  ## 
  ## Setting the width and height to 0 indicates that there are no bounds
  ## and is equivalent to having never made this request.
  ## 
  ## Setting width or height to a negative value is a protocol error.
  ## 
  ## The server should communicate this hint to an xdg_toplevel window with
  ## the xdg_toplevel.configure_bounds event for example.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverWindowV1).marshal_flags(
    RiverWindowV1Request_set_dimension_bounds.ord,
    nil,
    cast[ptr Proxy](riverWindowV1).get_version(),
    0,
    maxWidth,
    maxHeight,
  )

proc setUserData*(
    riverDecorationV1: ptr RiverDecorationV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](riverDecorationV1).set_user_data(user_data)

proc getUserData*(riverDecorationV1: ptr RiverDecorationV1): pointer {.inline.} =
  cast[ptr Proxy](riverDecorationV1).get_user_data()

proc getVersion*(riverDecorationV1: ptr RiverDecorationV1): uint32 {.inline.} =
  cast[ptr Proxy](riverDecorationV1).get_version()

proc destroy*(riverDecorationV1: ptr RiverDecorationV1) {.inline.} =
  ## destroy the decoration object
  ## 
  ## This request indicates that the client will no longer use the decoration
  ## object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverDecorationV1).marshal_flags(
    RiverDecorationV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverDecorationV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc setOffset*(
    riverDecorationV1: ptr RiverDecorationV1, x: int32, y: int32
) {.inline.} =
  ## set offset from the window's top left corner
  ## 
  ## This request sets the offset of the decoration surface from the top left
  ## corner of the window.
  ## 
  ## If this request is never sent, the x and y offsets are undefined by this
  ## protocol and left up to the compositor.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverDecorationV1).marshal_flags(
    RiverDecorationV1Request_set_offset.ord,
    nil,
    cast[ptr Proxy](riverDecorationV1).get_version(),
    0,
    x,
    y,
  )

proc syncNextCommit*(riverDecorationV1: ptr RiverDecorationV1) {.inline.} =
  ## sync next commit with other rendering state
  ## 
  ## Synchronize application of the next wl_surface.commit request on the
  ## decoration surface with rest of the state atomically applied with the
  ## next river_window_manager_v1.render_finish request.
  ## 
  ## The client must make a wl_surface.commit request on the decoration
  ## surface after this request and before the render_finish request, failure
  ## to do so is a protocol error.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverDecorationV1).marshal_flags(
    RiverDecorationV1Request_sync_next_commit.ord,
    nil,
    cast[ptr Proxy](riverDecorationV1).get_version(),
    0,
  )

proc setUserData*(
    riverShellSurfaceV1: ptr RiverShellSurfaceV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](riverShellSurfaceV1).set_user_data(user_data)

proc getUserData*(riverShellSurfaceV1: ptr RiverShellSurfaceV1): pointer {.inline.} =
  cast[ptr Proxy](riverShellSurfaceV1).get_user_data()

proc getVersion*(riverShellSurfaceV1: ptr RiverShellSurfaceV1): uint32 {.inline.} =
  cast[ptr Proxy](riverShellSurfaceV1).get_version()

proc destroy*(riverShellSurfaceV1: ptr RiverShellSurfaceV1) {.inline.} =
  ## destroy the shell surface object
  ## 
  ## This request indicates that the client will no longer use the shell
  ## surface object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverShellSurfaceV1).marshal_flags(
    RiverShellSurfaceV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverShellSurfaceV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc getNode*(
    riverShellSurfaceV1: ptr RiverShellSurfaceV1
): ptr RiverNodeV1 {.inline.} =
  ## get the shell surface's render list node
  ## 
  ## Get the node in the render list corresponding to the shell surface.
  ## 
  ## It is a protocol error to make this request more than once for a single
  ## shell surface.
  ## 
  cast[ptr RiverNodeV1](cast[ptr Proxy](riverShellSurfaceV1).marshal_flags(
    RiverShellSurfaceV1Request_get_node.ord,
    addr river_node_v1_interface,
    cast[ptr Proxy](riverShellSurfaceV1).get_version(),
    0,
    nil,
  ))

proc syncNextCommit*(riverShellSurfaceV1: ptr RiverShellSurfaceV1) {.inline.} =
  ## sync next surface commit to window manager commit
  ## 
  ## Synchronize application of the next wl_surface.commit request on the
  ## shell surface with rest of the rendering state atomically applied with
  ## the next river_window_manager_v1.render_finish request.
  ## 
  ## The client must make a wl_surface.commit request on the shell surface
  ## after this request and before the render_finish request, failure to do
  ## so is a protocol error.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverShellSurfaceV1).marshal_flags(
    RiverShellSurfaceV1Request_sync_next_commit.ord,
    nil,
    cast[ptr Proxy](riverShellSurfaceV1).get_version(),
    0,
  )

proc setUserData*(riverNodeV1: ptr RiverNodeV1, userData: pointer) {.inline.} =
  cast[ptr Proxy](riverNodeV1).set_user_data(user_data)

proc getUserData*(riverNodeV1: ptr RiverNodeV1): pointer {.inline.} =
  cast[ptr Proxy](riverNodeV1).get_user_data()

proc getVersion*(riverNodeV1: ptr RiverNodeV1): uint32 {.inline.} =
  cast[ptr Proxy](riverNodeV1).get_version()

proc destroy*(riverNodeV1: ptr RiverNodeV1) {.inline.} =
  ## destroy the decoration object
  ## 
  ## This request indicates that the client will no longer use the node
  ## object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverNodeV1).marshal_flags(
    RiverNodeV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverNodeV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc setPosition*(riverNodeV1: ptr RiverNodeV1, x: int32, y: int32) {.inline.} =
  ## set absolute position of the node
  ## 
  ## Set the absolute position of the node in the compositor's logical
  ## coordinate space. The x and y coordinates may be positive or negative.
  ## 
  ## Note that the position of a river_window_v1 refers to the position of
  ## the window content and is unaffected by the presence of borders or
  ## decoration surfaces.
  ## 
  ## If this request is never sent, the position of the node is undefined by
  ## this protocol and left up to the compositor.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverNodeV1).marshal_flags(
    RiverNodeV1Request_set_position.ord,
    nil,
    cast[ptr Proxy](riverNodeV1).get_version(),
    0,
    x,
    y,
  )

proc placeTop*(riverNodeV1: ptr RiverNodeV1) {.inline.} =
  ## place node above all other nodes
  ## 
  ## This request places the node above all other nodes in the compositor's
  ## render list.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverNodeV1).marshal_flags(
    RiverNodeV1Request_place_top.ord, nil, cast[ptr Proxy](riverNodeV1).get_version(), 0
  )

proc placeBottom*(riverNodeV1: ptr RiverNodeV1) {.inline.} =
  ## place node below all other nodes
  ## 
  ## This request places the node below all other nodes in the compositor's
  ## render list.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverNodeV1).marshal_flags(
    RiverNodeV1Request_place_bottom.ord,
    nil,
    cast[ptr Proxy](riverNodeV1).get_version(),
    0,
  )

proc placeAbove*(riverNodeV1: ptr RiverNodeV1, other: ptr RiverNodeV1) {.inline.} =
  ## place node above another node
  ## 
  ## This request places the node directly above another node in the
  ## compositor's render list.
  ## 
  ## Attempting to place a node above itself has no effect.
  ## 
  ## Given nodes A, B, C currently rendered in that order with C on top
  ## and A on the bottom, the following example demonstrates the behavior
  ## of this request and the meaning of "directly above":
  ##
  ## 1. A.place_above(C) -> B, C, A
  ## 2. A.place_above(B) -> B, A, C
  ## 3. B.place_above(A) -> A, B, C
  ##
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverNodeV1).marshal_flags(
    RiverNodeV1Request_place_above.ord,
    nil,
    cast[ptr Proxy](riverNodeV1).get_version(),
    0,
    other,
  )

proc placeBelow*(riverNodeV1: ptr RiverNodeV1, other: ptr RiverNodeV1) {.inline.} =
  ## place node below another node
  ## 
  ## This request places the node directly below another node in the
  ## compositor's render list.
  ## 
  ## Attempting to place a node below itself has no effect.
  ## 
  ## Given nodes A, B, C currently rendered in that order with C on top
  ## and A on the bottom, the following example demonstrates the behavior
  ## of this request and the meaning of "directly below":
  ##
  ## 1. C.place_below(A) -> C, A, B
  ## 2. C.place_below(B) -> A, C, B
  ## 3. B.place_below(C) -> A, B, C
  ##
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverNodeV1).marshal_flags(
    RiverNodeV1Request_place_below.ord,
    nil,
    cast[ptr Proxy](riverNodeV1).get_version(),
    0,
    other,
  )

type RiverOutputV1Listener* = object
  removed*: proc(data: pointer, riverOutputV1: ptr RiverOutputV1) {.nimcall.}
  output*:
    proc(data: pointer, riverOutputV1: ptr RiverOutputV1, name: uint32) {.nimcall.}
  position*: proc(data: pointer, riverOutputV1: ptr RiverOutputV1, x: int32, y: int32) {.
    nimcall
  .}
  dimensions*: proc(
    data: pointer, riverOutputV1: ptr RiverOutputV1, width: int32, height: int32
  ) {.nimcall.}
  captureSessions*:
    proc(data: pointer, riverOutputV1: ptr RiverOutputV1, count: uint32) {.nimcall.}

proc addListener*(
    riverOutputV1: ptr RiverOutputV1, listener: ptr RiverOutputV1Listener, data: pointer
): int {.inline.} =
  cast[ptr Proxy](riverOutputV1).add_listener(listener, data)

proc setUserData*(riverOutputV1: ptr RiverOutputV1, userData: pointer) {.inline.} =
  cast[ptr Proxy](riverOutputV1).set_user_data(user_data)

proc getUserData*(riverOutputV1: ptr RiverOutputV1): pointer {.inline.} =
  cast[ptr Proxy](riverOutputV1).get_user_data()

proc getVersion*(riverOutputV1: ptr RiverOutputV1): uint32 {.inline.} =
  cast[ptr Proxy](riverOutputV1).get_version()

proc destroy*(riverOutputV1: ptr RiverOutputV1) {.inline.} =
  ## destroy the output object
  ## 
  ## This request indicates that the client will no longer use the output
  ## object and that it may be safely destroyed.
  ## 
  ## This request should be made after the river_output_v1.removed event is
  ## received to complete destruction of the output.
  ## 
  cast[ptr Proxy](riverOutputV1).marshal_flags(
    RiverOutputV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverOutputV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc setPresentationMode*(riverOutputV1: ptr RiverOutputV1, mode: uint32) {.inline.} =
  ## set the preferred presentation mode
  ## 
  ## Set the preferred presentation mode of the output. The compositor should
  ## always respect the preference of the window manager if possible. If this
  ## request is never made, the preferred presentation mode is vsync.
  ## 
  ## This request modifies rendering state and may only be made as part of a
  ## render sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverOutputV1).marshal_flags(
    RiverOutputV1Request_set_presentation_mode.ord,
    nil,
    cast[ptr Proxy](riverOutputV1).get_version(),
    0,
    mode,
  )

type RiverSeatV1Listener* = object
  removed*: proc(data: pointer, riverSeatV1: ptr RiverSeatV1) {.nimcall.}
  seat*: proc(data: pointer, riverSeatV1: ptr RiverSeatV1, name: uint32) {.nimcall.}
  pointerEnter*: proc(
    data: pointer, riverSeatV1: ptr RiverSeatV1, window: ptr RiverWindowV1
  ) {.nimcall.}
  pointerLeave*: proc(data: pointer, riverSeatV1: ptr RiverSeatV1) {.nimcall.}
  windowInteraction*: proc(
    data: pointer, riverSeatV1: ptr RiverSeatV1, window: ptr RiverWindowV1
  ) {.nimcall.}
  shellSurfaceInteraction*: proc(
    data: pointer, riverSeatV1: ptr RiverSeatV1, shellSurface: ptr RiverShellSurfaceV1
  ) {.nimcall.}
  opDelta*:
    proc(data: pointer, riverSeatV1: ptr RiverSeatV1, dx: int32, dy: int32) {.nimcall.}
  opRelease*: proc(data: pointer, riverSeatV1: ptr RiverSeatV1) {.nimcall.}
  pointerPosition*:
    proc(data: pointer, riverSeatV1: ptr RiverSeatV1, x: int32, y: int32) {.nimcall.}

proc addListener*(
    riverSeatV1: ptr RiverSeatV1, listener: ptr RiverSeatV1Listener, data: pointer
): int {.inline.} =
  cast[ptr Proxy](riverSeatV1).add_listener(listener, data)

proc setUserData*(riverSeatV1: ptr RiverSeatV1, userData: pointer) {.inline.} =
  cast[ptr Proxy](riverSeatV1).set_user_data(user_data)

proc getUserData*(riverSeatV1: ptr RiverSeatV1): pointer {.inline.} =
  cast[ptr Proxy](riverSeatV1).get_user_data()

proc getVersion*(riverSeatV1: ptr RiverSeatV1): uint32 {.inline.} =
  cast[ptr Proxy](riverSeatV1).get_version()

proc destroy*(riverSeatV1: ptr RiverSeatV1) {.inline.} =
  ## destroy the seat object
  ## 
  ## This request indicates that the client will no longer use the seat
  ## object and that it may be safely destroyed.
  ## 
  ## This request should be made after the river_seat_v1.removed event is
  ## received to complete destruction of the seat.
  ## 
  cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverSeatV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc focusWindow*(riverSeatV1: ptr RiverSeatV1, window: ptr RiverWindowV1) {.inline.} =
  ## give keyboard focus to a window
  ## 
  ## Request that the compositor send keyboard input to the given window.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_focus_window.ord,
    nil,
    cast[ptr Proxy](riverSeatV1).get_version(),
    0,
    window,
  )

proc focusShellSurface*(
    riverSeatV1: ptr RiverSeatV1, shellSurface: ptr RiverShellSurfaceV1
) {.inline.} =
  ## give keyboard focus to a shell_surface
  ## 
  ## Request that the compositor send keyboard input to the given shell
  ## surface.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_focus_shell_surface.ord,
    nil,
    cast[ptr Proxy](riverSeatV1).get_version(),
    0,
    shellSurface,
  )

proc clearFocus*(riverSeatV1: ptr RiverSeatV1) {.inline.} =
  ## clear keyboard focus
  ## 
  ## Request that the compositor not send keyboard input to any client.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_clear_focus.ord,
    nil,
    cast[ptr Proxy](riverSeatV1).get_version(),
    0,
  )

proc opStartPointer*(riverSeatV1: ptr RiverSeatV1) {.inline.} =
  ## start an interactive pointer operation
  ## 
  ## Start an interactive pointer operation. During the operation, op_delta
  ## events will be sent based on pointer input.
  ## 
  ## When all pointer buttons are released, the op_release event is sent.
  ## 
  ## The pointer operation continues until the op_end request is made during
  ## a manage sequence and that manage sequence is finished.
  ## 
  ## The window manager may use this operation to implement interactive
  ## move/resize of windows by setting the position of windows and proposing
  ## dimensions based off of the op_delta events.
  ## 
  ## This request is ignored if an operation is already in progress.
  ## 
  ## The compositor must ensure that no client has pointer focus from this
  ## seat during the pointer operation. This means that the window manager
  ## has control over the pointer's cursor surface/shape during the pointer
  ## operation. See the river_seat_v1 description.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_op_start_pointer.ord,
    nil,
    cast[ptr Proxy](riverSeatV1).get_version(),
    0,
  )

proc opEnd*(riverSeatV1: ptr RiverSeatV1) {.inline.} =
  ## end an interactive operation
  ## 
  ## End an interactive operation.
  ## 
  ## This request is ignored if there is no operation in progress.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_op_end.ord, nil, cast[ptr Proxy](riverSeatV1).get_version(), 0
  )

proc getPointerBinding*(
    riverSeatV1: ptr RiverSeatV1, button: uint32, modifiers: uint32
): ptr RiverPointerBindingV1 {.inline.} =
  ## define a new pointer binding
  ## 
  ## Define a pointer binding in terms of a pointer button, keyboard
  ## modifiers, and other configurable properties.
  ## 
  ## The button argument is a Linux input event code defined in the
  ## linux/input-event-codes.h header file (e.g. BTN_RIGHT).
  ## 
  ## The new pointer binding is not enabled until initial configuration is
  ## completed and the enable request is made during a manage sequence.
  ## 
  cast[ptr RiverPointerBindingV1](cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_get_pointer_binding.ord,
    addr river_pointer_binding_v1_interface,
    cast[ptr Proxy](riverSeatV1).get_version(),
    0,
    nil,
    button,
    modifiers,
  ))

proc setXcursorTheme*(
    riverSeatV1: ptr RiverSeatV1, name: cstring, size: uint32
) {.inline.} =
  ## set the xcursor theme for the seat
  ## 
  ## Set the XCursor theme for the seat. This theme is used for cursors
  ## rendered by the compositor, but not necessarily for cursors rendered by
  ## clients.
  ## 
  ## Note: The window manager may also wish to set the XCURSOR_THEME and
  ## XCURSOR_SIZE environment variable for programs it starts.
  ## 
  cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_set_xcursor_theme.ord,
    nil,
    cast[ptr Proxy](riverSeatV1).get_version(),
    0,
    name,
    size,
  )

proc pointerWarp*(riverSeatV1: ptr RiverSeatV1, x: int32, y: int32) {.inline.} =
  ## warp the pointer to a given position
  ## 
  ## Warp the pointer to the given position in the compositor's logical
  ## coordinate space.
  ## 
  ## If the given position is outside the bounds of all outputs, the pointer
  ## will be warped to the closest point inside an output instead.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverSeatV1).marshal_flags(
    RiverSeatV1Request_pointer_warp.ord,
    nil,
    cast[ptr Proxy](riverSeatV1).get_version(),
    0,
    x,
    y,
  )

type RiverPointerBindingV1Listener* = object
  pressed*:
    proc(data: pointer, riverPointerBindingV1: ptr RiverPointerBindingV1) {.nimcall.}
  released*:
    proc(data: pointer, riverPointerBindingV1: ptr RiverPointerBindingV1) {.nimcall.}

proc addListener*(
    riverPointerBindingV1: ptr RiverPointerBindingV1,
    listener: ptr RiverPointerBindingV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](riverPointerBindingV1).add_listener(listener, data)

proc setUserData*(
    riverPointerBindingV1: ptr RiverPointerBindingV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](riverPointerBindingV1).set_user_data(user_data)

proc getUserData*(
    riverPointerBindingV1: ptr RiverPointerBindingV1
): pointer {.inline.} =
  cast[ptr Proxy](riverPointerBindingV1).get_user_data()

proc getVersion*(riverPointerBindingV1: ptr RiverPointerBindingV1): uint32 {.inline.} =
  cast[ptr Proxy](riverPointerBindingV1).get_version()

proc destroy*(riverPointerBindingV1: ptr RiverPointerBindingV1) {.inline.} =
  ## destroy the pointer binding object
  ## 
  ## This request indicates that the client will no longer use the pointer
  ## binding object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverPointerBindingV1).marshal_flags(
    RiverPointerBindingV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverPointerBindingV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc enable*(riverPointerBindingV1: ptr RiverPointerBindingV1) {.inline.} =
  ## enable the pointer binding
  ## 
  ## This request should be made after all initial configuration has been
  ## completed and the window manager wishes the pointer binding to be able
  ## to be triggered.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverPointerBindingV1).marshal_flags(
    RiverPointerBindingV1Request_enable.ord,
    nil,
    cast[ptr Proxy](riverPointerBindingV1).get_version(),
    0,
  )

proc disable*(riverPointerBindingV1: ptr RiverPointerBindingV1) {.inline.} =
  ## disable the pointer binding
  ## 
  ## This request may be used to temporarily disable the pointer binding. It
  ## may be later re-enabled with the enable request.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverPointerBindingV1).marshal_flags(
    RiverPointerBindingV1Request_disable.ord,
    nil,
    cast[ptr Proxy](riverPointerBindingV1).get_version(),
    0,
  )
