# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var riverWindowManagementV1_types: array[33, ptr Interface]
type RiverDecorationV1* = object
type RiverNodeV1* = object
type RiverOutputV1* = object
type RiverPointerBindingV1* = object
type RiverSeatV1* = object
type RiverShellSurfaceV1* = object
type RiverWindowManagerV1* = object
type RiverWindowV1* = object

let
  river_window_manager_v1_requests {.exportc.} = [
    Message(
      name: "stop", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "destroy", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "manage_finish",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "manage_dirty",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "render_finish",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "get_shell_surface",
      signature: "no",
      types: addr river_window_management_v1_types[6],
    ),
    Message(
      name: "exit_session",
      signature: "4",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_window_manager_v1_events {.exportc.} = [
    Message(
      name: "unavailable",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "finished", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "manage_start",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "render_start",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "session_locked",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "session_unlocked",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "window", signature: "n", types: addr river_window_management_v1_types[8]
    ),
    Message(
      name: "output", signature: "n", types: addr river_window_management_v1_types[9]
    ),
    Message(
      name: "seat", signature: "n", types: addr river_window_management_v1_types[10]
    ),
  ]

  river_window_manager_v1_interface* {.exportc.} = Interface(
    name: "river_window_manager_v1",
    version: 5,
    method_count: 7,
    methods: addr river_window_manager_v1_requests[0],
    event_count: 9,
    events: addr river_window_manager_v1_events[0],
  )

  river_window_v1_requests {.exportc.} = [
    Message(
      name: "destroy", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "close", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "get_node", signature: "n", types: addr river_window_management_v1_types[11]
    ),
    Message(
      name: "propose_dimensions",
      signature: "ii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "hide", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "show", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "use_csd", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "use_ssd", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "set_borders",
      signature: "uiuuuu",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "set_tiled", signature: "u", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "get_decoration_above",
      signature: "no",
      types: addr river_window_management_v1_types[12],
    ),
    Message(
      name: "get_decoration_below",
      signature: "no",
      types: addr river_window_management_v1_types[14],
    ),
    Message(
      name: "inform_resize_start",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "inform_resize_end",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "set_capabilities",
      signature: "u",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "inform_maximized",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "inform_unmaximized",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "inform_fullscreen",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "inform_not_fullscreen",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "fullscreen",
      signature: "o",
      types: addr river_window_management_v1_types[16],
    ),
    Message(
      name: "exit_fullscreen",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "set_clip_box",
      signature: "2iiii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "set_content_clip_box",
      signature: "3iiii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "set_dimension_bounds",
      signature: "4ii",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_window_v1_events {.exportc.} = [
    Message(
      name: "closed", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "dimensions_hint",
      signature: "iiii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "dimensions",
      signature: "ii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "app_id", signature: "?s", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "title", signature: "?s", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "parent", signature: "?o", types: addr river_window_management_v1_types[17]
    ),
    Message(
      name: "decoration_hint",
      signature: "u",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "pointer_move_requested",
      signature: "o",
      types: addr river_window_management_v1_types[18],
    ),
    Message(
      name: "pointer_resize_requested",
      signature: "ou",
      types: addr river_window_management_v1_types[19],
    ),
    Message(
      name: "show_window_menu_requested",
      signature: "ii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "maximize_requested",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "unmaximize_requested",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "fullscreen_requested",
      signature: "?o",
      types: addr river_window_management_v1_types[21],
    ),
    Message(
      name: "exit_fullscreen_requested",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "minimize_requested",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "unreliable_pid",
      signature: "2i",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "presentation_hint",
      signature: "4u",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "identifier",
      signature: "4s",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "capture_sessions",
      signature: "5u",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_window_v1_interface* {.exportc.} = Interface(
    name: "river_window_v1",
    version: 5,
    method_count: 24,
    methods: addr river_window_v1_requests[0],
    event_count: 19,
    events: addr river_window_v1_events[0],
  )

  river_decoration_v1_requests {.exportc.} = [
    Message(
      name: "destroy", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "set_offset",
      signature: "ii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "sync_next_commit",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_decoration_v1_interface* {.exportc.} = Interface(
    name: "river_decoration_v1",
    version: 5,
    method_count: 3,
    methods: addr river_decoration_v1_requests[0],
  )

  river_shell_surface_v1_requests {.exportc.} = [
    Message(
      name: "destroy", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "get_node", signature: "n", types: addr river_window_management_v1_types[22]
    ),
    Message(
      name: "sync_next_commit",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_shell_surface_v1_interface* {.exportc.} = Interface(
    name: "river_shell_surface_v1",
    version: 5,
    method_count: 3,
    methods: addr river_shell_surface_v1_requests[0],
  )

  river_node_v1_requests {.exportc.} = [
    Message(
      name: "destroy", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "set_position",
      signature: "ii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "place_top", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "place_bottom",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "place_above",
      signature: "o",
      types: addr river_window_management_v1_types[23],
    ),
    Message(
      name: "place_below",
      signature: "o",
      types: addr river_window_management_v1_types[24],
    ),
  ]

  river_node_v1_interface* {.exportc.} = Interface(
    name: "river_node_v1",
    version: 5,
    method_count: 6,
    methods: addr river_node_v1_requests[0],
  )

  river_output_v1_requests {.exportc.} = [
    Message(
      name: "destroy", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "set_presentation_mode",
      signature: "4u",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_output_v1_events {.exportc.} = [
    Message(
      name: "removed", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "wl_output", signature: "u", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "position", signature: "ii", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "dimensions",
      signature: "ii",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "capture_sessions",
      signature: "5u",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_output_v1_interface* {.exportc.} = Interface(
    name: "river_output_v1",
    version: 5,
    method_count: 2,
    methods: addr river_output_v1_requests[0],
    event_count: 5,
    events: addr river_output_v1_events[0],
  )

  river_seat_v1_requests {.exportc.} = [
    Message(
      name: "destroy", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "focus_window",
      signature: "o",
      types: addr river_window_management_v1_types[25],
    ),
    Message(
      name: "focus_shell_surface",
      signature: "o",
      types: addr river_window_management_v1_types[26],
    ),
    Message(
      name: "clear_focus",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "op_start_pointer",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "op_end", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "get_pointer_binding",
      signature: "nuu",
      types: addr river_window_management_v1_types[27],
    ),
    Message(
      name: "set_xcursor_theme",
      signature: "2su",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "pointer_warp",
      signature: "3ii",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_seat_v1_events {.exportc.} = [
    Message(
      name: "removed", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "wl_seat", signature: "u", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "pointer_enter",
      signature: "o",
      types: addr river_window_management_v1_types[30],
    ),
    Message(
      name: "pointer_leave",
      signature: "",
      types: addr river_window_management_v1_types[0],
    ),
    Message(
      name: "window_interaction",
      signature: "o",
      types: addr river_window_management_v1_types[31],
    ),
    Message(
      name: "shell_surface_interaction",
      signature: "o",
      types: addr river_window_management_v1_types[32],
    ),
    Message(
      name: "op_delta", signature: "ii", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "op_release", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "pointer_position",
      signature: "2ii",
      types: addr river_window_management_v1_types[0],
    ),
  ]

  river_seat_v1_interface* {.exportc.} = Interface(
    name: "river_seat_v1",
    version: 5,
    method_count: 9,
    methods: addr river_seat_v1_requests[0],
    event_count: 9,
    events: addr river_seat_v1_events[0],
  )

  river_pointer_binding_v1_requests {.exportc.} = [
    Message(
      name: "destroy", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "enable", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "disable", signature: "", types: addr river_window_management_v1_types[0]
    ),
  ]

  river_pointer_binding_v1_events {.exportc.} = [
    Message(
      name: "pressed", signature: "", types: addr river_window_management_v1_types[0]
    ),
    Message(
      name: "released", signature: "", types: addr river_window_management_v1_types[0]
    ),
  ]

  river_pointer_binding_v1_interface* {.exportc.} = Interface(
    name: "river_pointer_binding_v1",
    version: 5,
    method_count: 3,
    methods: addr river_pointer_binding_v1_requests[0],
    event_count: 2,
    events: addr river_pointer_binding_v1_events[0],
  )

type RiverWindowManagerV1Error* {.size: sizeof(uint32).} = enum
  error_sequence_order = 0
  error_role = 1
  error_unresponsive = 2

func since*(e: RiverWindowManagerV1Error): int =
  case e
  of error_sequence_order: 1
  of error_role: 1
  of error_unresponsive: 1
proc isValid*(e: RiverWindowManagerV1Error, version: int): bool =
  version >= e.since

type RiverWindowV1Error* {.size: sizeof(uint32).} = enum
  error_node_exists = 0
  error_invalid_dimensions = 1
  error_invalid_border = 2
  error_invalid_clip_box = 3

func since*(e: RiverWindowV1Error): int =
  case e
  of error_node_exists: 1
  of error_invalid_dimensions: 1
  of error_invalid_border: 1
  of error_invalid_clip_box: 1
proc isValid*(e: RiverWindowV1Error, version: int): bool =
  version >= e.since

type RiverWindowV1DecorationHint* {.size: sizeof(uint32).} = enum
  decoration_hint_only_supports_csd = 0
  decoration_hint_prefers_csd = 1
  decoration_hint_prefers_ssd = 2
  decoration_hint_no_preference = 3

func since*(e: RiverWindowV1DecorationHint): int =
  case e
  of decoration_hint_only_supports_csd: 1
  of decoration_hint_prefers_csd: 1
  of decoration_hint_prefers_ssd: 1
  of decoration_hint_no_preference: 1
proc isValid*(e: RiverWindowV1DecorationHint, version: int): bool =
  version >= e.since

type RiverWindowV1Edges* {.size: sizeof(uint32).} = enum
  edges_none = 0
  edges_top = 1
  edges_bottom = 2
  edges_left = 4
  edges_right = 8

func since*(e: RiverWindowV1Edges): int =
  case e
  of edges_none: 1
  of edges_top: 1
  of edges_bottom: 1
  of edges_left: 1
  of edges_right: 1
proc isValid*(e: RiverWindowV1Edges, version: int): bool =
  version >= e.since

type RiverWindowV1Capabilities* {.size: sizeof(uint32).} = enum
  capabilities_window_menu = 1
  capabilities_maximize = 2
  capabilities_fullscreen = 4
  capabilities_minimize = 8

func since*(e: RiverWindowV1Capabilities): int =
  case e
  of capabilities_window_menu: 1
  of capabilities_maximize: 1
  of capabilities_fullscreen: 1
  of capabilities_minimize: 1
proc isValid*(e: RiverWindowV1Capabilities, version: int): bool =
  version >= e.since

type RiverDecorationV1Error* {.size: sizeof(uint32).} = enum
  error_no_commit = 0

func since*(e: RiverDecorationV1Error): int =
  case e
  of error_no_commit: 1
proc isValid*(e: RiverDecorationV1Error, version: int): bool =
  version >= e.since

type RiverShellSurfaceV1Error* {.size: sizeof(uint32).} = enum
  error_node_exists = 0
  error_no_commit = 1

func since*(e: RiverShellSurfaceV1Error): int =
  case e
  of error_node_exists: 1
  of error_no_commit: 1
proc isValid*(e: RiverShellSurfaceV1Error, version: int): bool =
  version >= e.since

type RiverOutputV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_presentation_mode = 0

func since*(e: RiverOutputV1Error): int =
  case e
  of error_invalid_presentation_mode: 4
proc isValid*(e: RiverOutputV1Error, version: int): bool =
  version >= e.since

type RiverOutputV1PresentationMode* {.size: sizeof(uint32).} = enum
  presentation_mode_vsync = 0
  presentation_mode_async = 1

func since*(e: RiverOutputV1PresentationMode): int =
  case e
  of presentation_mode_vsync: 4
  of presentation_mode_async: 4
proc isValid*(e: RiverOutputV1PresentationMode, version: int): bool =
  version >= e.since

type RiverSeatV1Modifiers* {.size: sizeof(uint32).} = enum
  modifiers_none = 0
  modifiers_shift = 1
  modifiers_ctrl = 4
  modifiers_mod1 = 8
  modifiers_mod3 = 32
  modifiers_mod4 = 64
  modifiers_mod5 = 128

func since*(e: RiverSeatV1Modifiers): int =
  case e
  of modifiers_none: 1
  of modifiers_shift: 1
  of modifiers_ctrl: 1
  of modifiers_mod1: 1
  of modifiers_mod3: 1
  of modifiers_mod4: 1
  of modifiers_mod5: 1
proc isValid*(e: RiverSeatV1Modifiers, version: int): bool =
  version >= e.since

type RiverWindowManagerV1Event* {.size: sizeof(uint32).} = enum
  RiverWindowManagerV1Event_unavailable
  RiverWindowManagerV1Event_finished
  RiverWindowManagerV1Event_manage_start
  RiverWindowManagerV1Event_render_start
  RiverWindowManagerV1Event_session_locked
  RiverWindowManagerV1Event_session_unlocked
  RiverWindowManagerV1Event_window
  RiverWindowManagerV1Event_output
  RiverWindowManagerV1Event_seat

proc since*(e: RiverWindowManagerV1Event): int =
  case e
  of RiverWindowManagerV1Event_unavailable: 1
  of RiverWindowManagerV1Event_finished: 1
  of RiverWindowManagerV1Event_manage_start: 1
  of RiverWindowManagerV1Event_render_start: 1
  of RiverWindowManagerV1Event_session_locked: 1
  of RiverWindowManagerV1Event_session_unlocked: 1
  of RiverWindowManagerV1Event_window: 1
  of RiverWindowManagerV1Event_output: 1
  of RiverWindowManagerV1Event_seat: 1

type RiverWindowManagerV1Request* {.size: sizeof(uint32).} = enum
  RiverWindowManagerV1Request_stop
  RiverWindowManagerV1Request_destroy
  RiverWindowManagerV1Request_manage_finish
  RiverWindowManagerV1Request_manage_dirty
  RiverWindowManagerV1Request_render_finish
  RiverWindowManagerV1Request_get_shell_surface
  RiverWindowManagerV1Request_exit_session

proc since*(e: RiverWindowManagerV1Request): int =
  case e
  of RiverWindowManagerV1Request_stop: 1
  of RiverWindowManagerV1Request_destroy: 1
  of RiverWindowManagerV1Request_manage_finish: 1
  of RiverWindowManagerV1Request_manage_dirty: 1
  of RiverWindowManagerV1Request_render_finish: 1
  of RiverWindowManagerV1Request_get_shell_surface: 1
  of RiverWindowManagerV1Request_exit_session: 4

type RiverWindowV1Event* {.size: sizeof(uint32).} = enum
  RiverWindowV1Event_closed
  RiverWindowV1Event_dimensions_hint
  RiverWindowV1Event_dimensions
  RiverWindowV1Event_app_id
  RiverWindowV1Event_title
  RiverWindowV1Event_parent
  RiverWindowV1Event_decoration_hint
  RiverWindowV1Event_pointer_move_requested
  RiverWindowV1Event_pointer_resize_requested
  RiverWindowV1Event_show_window_menu_requested
  RiverWindowV1Event_maximize_requested
  RiverWindowV1Event_unmaximize_requested
  RiverWindowV1Event_fullscreen_requested
  RiverWindowV1Event_exit_fullscreen_requested
  RiverWindowV1Event_minimize_requested
  RiverWindowV1Event_unreliable_pid
  RiverWindowV1Event_presentation_hint
  RiverWindowV1Event_identifier
  RiverWindowV1Event_capture_sessions

proc since*(e: RiverWindowV1Event): int =
  case e
  of RiverWindowV1Event_closed: 1
  of RiverWindowV1Event_dimensions_hint: 1
  of RiverWindowV1Event_dimensions: 1
  of RiverWindowV1Event_app_id: 1
  of RiverWindowV1Event_title: 1
  of RiverWindowV1Event_parent: 1
  of RiverWindowV1Event_decoration_hint: 1
  of RiverWindowV1Event_pointer_move_requested: 1
  of RiverWindowV1Event_pointer_resize_requested: 1
  of RiverWindowV1Event_show_window_menu_requested: 1
  of RiverWindowV1Event_maximize_requested: 1
  of RiverWindowV1Event_unmaximize_requested: 1
  of RiverWindowV1Event_fullscreen_requested: 1
  of RiverWindowV1Event_exit_fullscreen_requested: 1
  of RiverWindowV1Event_minimize_requested: 1
  of RiverWindowV1Event_unreliable_pid: 2
  of RiverWindowV1Event_presentation_hint: 4
  of RiverWindowV1Event_identifier: 4
  of RiverWindowV1Event_capture_sessions: 5

type RiverWindowV1Request* {.size: sizeof(uint32).} = enum
  RiverWindowV1Request_destroy
  RiverWindowV1Request_close
  RiverWindowV1Request_get_node
  RiverWindowV1Request_propose_dimensions
  RiverWindowV1Request_hide
  RiverWindowV1Request_show
  RiverWindowV1Request_use_csd
  RiverWindowV1Request_use_ssd
  RiverWindowV1Request_set_borders
  RiverWindowV1Request_set_tiled
  RiverWindowV1Request_get_decoration_above
  RiverWindowV1Request_get_decoration_below
  RiverWindowV1Request_inform_resize_start
  RiverWindowV1Request_inform_resize_end
  RiverWindowV1Request_set_capabilities
  RiverWindowV1Request_inform_maximized
  RiverWindowV1Request_inform_unmaximized
  RiverWindowV1Request_inform_fullscreen
  RiverWindowV1Request_inform_not_fullscreen
  RiverWindowV1Request_fullscreen
  RiverWindowV1Request_exit_fullscreen
  RiverWindowV1Request_set_clip_box
  RiverWindowV1Request_set_content_clip_box
  RiverWindowV1Request_set_dimension_bounds

proc since*(e: RiverWindowV1Request): int =
  case e
  of RiverWindowV1Request_destroy: 1
  of RiverWindowV1Request_close: 1
  of RiverWindowV1Request_get_node: 1
  of RiverWindowV1Request_propose_dimensions: 1
  of RiverWindowV1Request_hide: 1
  of RiverWindowV1Request_show: 1
  of RiverWindowV1Request_use_csd: 1
  of RiverWindowV1Request_use_ssd: 1
  of RiverWindowV1Request_set_borders: 1
  of RiverWindowV1Request_set_tiled: 1
  of RiverWindowV1Request_get_decoration_above: 1
  of RiverWindowV1Request_get_decoration_below: 1
  of RiverWindowV1Request_inform_resize_start: 1
  of RiverWindowV1Request_inform_resize_end: 1
  of RiverWindowV1Request_set_capabilities: 1
  of RiverWindowV1Request_inform_maximized: 1
  of RiverWindowV1Request_inform_unmaximized: 1
  of RiverWindowV1Request_inform_fullscreen: 1
  of RiverWindowV1Request_inform_not_fullscreen: 1
  of RiverWindowV1Request_fullscreen: 1
  of RiverWindowV1Request_exit_fullscreen: 1
  of RiverWindowV1Request_set_clip_box: 2
  of RiverWindowV1Request_set_content_clip_box: 3
  of RiverWindowV1Request_set_dimension_bounds: 4

type RiverDecorationV1Request* {.size: sizeof(uint32).} = enum
  RiverDecorationV1Request_destroy
  RiverDecorationV1Request_set_offset
  RiverDecorationV1Request_sync_next_commit

proc since*(e: RiverDecorationV1Request): int =
  case e
  of RiverDecorationV1Request_destroy: 1
  of RiverDecorationV1Request_set_offset: 1
  of RiverDecorationV1Request_sync_next_commit: 1

type RiverShellSurfaceV1Request* {.size: sizeof(uint32).} = enum
  RiverShellSurfaceV1Request_destroy
  RiverShellSurfaceV1Request_get_node
  RiverShellSurfaceV1Request_sync_next_commit

proc since*(e: RiverShellSurfaceV1Request): int =
  case e
  of RiverShellSurfaceV1Request_destroy: 1
  of RiverShellSurfaceV1Request_get_node: 1
  of RiverShellSurfaceV1Request_sync_next_commit: 1

type RiverNodeV1Request* {.size: sizeof(uint32).} = enum
  RiverNodeV1Request_destroy
  RiverNodeV1Request_set_position
  RiverNodeV1Request_place_top
  RiverNodeV1Request_place_bottom
  RiverNodeV1Request_place_above
  RiverNodeV1Request_place_below

proc since*(e: RiverNodeV1Request): int =
  case e
  of RiverNodeV1Request_destroy: 1
  of RiverNodeV1Request_set_position: 1
  of RiverNodeV1Request_place_top: 1
  of RiverNodeV1Request_place_bottom: 1
  of RiverNodeV1Request_place_above: 1
  of RiverNodeV1Request_place_below: 1

type RiverOutputV1Event* {.size: sizeof(uint32).} = enum
  RiverOutputV1Event_removed
  RiverOutputV1Event_wl_output
  RiverOutputV1Event_position
  RiverOutputV1Event_dimensions
  RiverOutputV1Event_capture_sessions

proc since*(e: RiverOutputV1Event): int =
  case e
  of RiverOutputV1Event_removed: 1
  of RiverOutputV1Event_wl_output: 1
  of RiverOutputV1Event_position: 1
  of RiverOutputV1Event_dimensions: 1
  of RiverOutputV1Event_capture_sessions: 5

type RiverOutputV1Request* {.size: sizeof(uint32).} = enum
  RiverOutputV1Request_destroy
  RiverOutputV1Request_set_presentation_mode

proc since*(e: RiverOutputV1Request): int =
  case e
  of RiverOutputV1Request_destroy: 1
  of RiverOutputV1Request_set_presentation_mode: 4

type RiverSeatV1Event* {.size: sizeof(uint32).} = enum
  RiverSeatV1Event_removed
  RiverSeatV1Event_wl_seat
  RiverSeatV1Event_pointer_enter
  RiverSeatV1Event_pointer_leave
  RiverSeatV1Event_window_interaction
  RiverSeatV1Event_shell_surface_interaction
  RiverSeatV1Event_op_delta
  RiverSeatV1Event_op_release
  RiverSeatV1Event_pointer_position

proc since*(e: RiverSeatV1Event): int =
  case e
  of RiverSeatV1Event_removed: 1
  of RiverSeatV1Event_wl_seat: 1
  of RiverSeatV1Event_pointer_enter: 1
  of RiverSeatV1Event_pointer_leave: 1
  of RiverSeatV1Event_window_interaction: 1
  of RiverSeatV1Event_shell_surface_interaction: 1
  of RiverSeatV1Event_op_delta: 1
  of RiverSeatV1Event_op_release: 1
  of RiverSeatV1Event_pointer_position: 2

type RiverSeatV1Request* {.size: sizeof(uint32).} = enum
  RiverSeatV1Request_destroy
  RiverSeatV1Request_focus_window
  RiverSeatV1Request_focus_shell_surface
  RiverSeatV1Request_clear_focus
  RiverSeatV1Request_op_start_pointer
  RiverSeatV1Request_op_end
  RiverSeatV1Request_get_pointer_binding
  RiverSeatV1Request_set_xcursor_theme
  RiverSeatV1Request_pointer_warp

proc since*(e: RiverSeatV1Request): int =
  case e
  of RiverSeatV1Request_destroy: 1
  of RiverSeatV1Request_focus_window: 1
  of RiverSeatV1Request_focus_shell_surface: 1
  of RiverSeatV1Request_clear_focus: 1
  of RiverSeatV1Request_op_start_pointer: 1
  of RiverSeatV1Request_op_end: 1
  of RiverSeatV1Request_get_pointer_binding: 1
  of RiverSeatV1Request_set_xcursor_theme: 2
  of RiverSeatV1Request_pointer_warp: 3

type RiverPointerBindingV1Event* {.size: sizeof(uint32).} = enum
  RiverPointerBindingV1Event_pressed
  RiverPointerBindingV1Event_released

proc since*(e: RiverPointerBindingV1Event): int =
  case e
  of RiverPointerBindingV1Event_pressed: 1
  of RiverPointerBindingV1Event_released: 1

type RiverPointerBindingV1Request* {.size: sizeof(uint32).} = enum
  RiverPointerBindingV1Request_destroy
  RiverPointerBindingV1Request_enable
  RiverPointerBindingV1Request_disable

proc since*(e: RiverPointerBindingV1Request): int =
  case e
  of RiverPointerBindingV1Request_destroy: 1
  of RiverPointerBindingV1Request_enable: 1
  of RiverPointerBindingV1Request_disable: 1

riverWindowManagementV1_types = [
  nil,
  nil,
  nil,
  nil,
  nil,
  nil,
  addr river_shell_surface_v1_interface,
  addr wl_surface_interface,
  addr river_window_v1_interface,
  addr river_output_v1_interface,
  addr river_seat_v1_interface,
  addr river_node_v1_interface,
  addr river_decoration_v1_interface,
  addr wl_surface_interface,
  addr river_decoration_v1_interface,
  addr wl_surface_interface,
  addr river_output_v1_interface,
  addr river_window_v1_interface,
  addr river_seat_v1_interface,
  addr river_seat_v1_interface,
  nil,
  addr river_output_v1_interface,
  addr river_node_v1_interface,
  addr river_node_v1_interface,
  addr river_node_v1_interface,
  addr river_window_v1_interface,
  addr river_shell_surface_v1_interface,
  addr river_pointer_binding_v1_interface,
  nil,
  nil,
  addr river_window_v1_interface,
  addr river_window_v1_interface,
  addr river_shell_surface_v1_interface,
]
