# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/server
import wayland/native/common
import code
export code

## The river_window_management_v1 SERVER protocol
## ##############################################
## 
## Interfaces
## ==========
## 
## * river_window_manager_v1
## * river_window_v1
## * river_decoration_v1
## * river_shell_surface_v1
## * river_node_v1
## * river_output_v1
## * river_seat_v1
## * river_pointer_binding_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2024 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverWindowManagerV1Interface* = object
  stop*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  manageFinish*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  manageDirty*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  renderFinish*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  getShellSurface*: proc(
    client: ptr Client, resource: ptr Resource, id: uint32, surface: ptr Resource
  ) {.nimcall.}
  exitSession*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc riverWindowManagerV1SendUnavailable*(
    resource: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_unavailable".} =
  ## Sends an unavailable event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowManagerV1Event_unavailable.ord)

proc riverWindowManagerV1SendFinished*(
    resource: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_finished".} =
  ## Sends an finished event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowManagerV1Event_finished.ord)

proc riverWindowManagerV1SendManageStart*(
    resource: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_manage_start".} =
  ## Sends an manage_start event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowManagerV1Event_manage_start.ord)

proc riverWindowManagerV1SendRenderStart*(
    resource: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_render_start".} =
  ## Sends an render_start event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowManagerV1Event_render_start.ord)

proc riverWindowManagerV1SendSessionLocked*(
    resource: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_session_locked".} =
  ## Sends an session_locked event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowManagerV1Event_session_locked.ord)

proc riverWindowManagerV1SendSessionUnlocked*(
    resource: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_session_unlocked".} =
  ## Sends an session_unlocked event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowManagerV1Event_session_unlocked.ord)

proc riverWindowManagerV1SendWindow*(
    resource: ptr Resource, id: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_window".} =
  ## Sends an window event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *id*: new window
  resource.post_event(RiverWindowManagerV1Event_window.ord, id)

proc riverWindowManagerV1SendOutput*(
    resource: ptr Resource, id: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_output".} =
  ## Sends an output event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *id*: new output
  resource.post_event(RiverWindowManagerV1Event_output.ord, id)

proc riverWindowManagerV1SendSeat*(
    resource: ptr Resource, id: ptr Resource
) {.inline, exportc: "river_window_manager_v1_send_seat".} =
  ## Sends an seat event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *id*: new seat
  resource.post_event(RiverWindowManagerV1Event_seat.ord, id)

type RiverWindowV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  close*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  getNode*: proc(client: ptr Client, resource: ptr Resource, id: uint32) {.nimcall.}
  proposeDimensions*: proc(
    client: ptr Client, resource: ptr Resource, width: int32, height: int32
  ) {.nimcall.}
  hide*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  show*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  useCsd*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  useSsd*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  setBorders*: proc(
    client: ptr Client,
    resource: ptr Resource,
    edges: uint32,
    width: int32,
    r: uint32,
    g: uint32,
    b: uint32,
    a: uint32,
  ) {.nimcall.}
  setTiled*: proc(client: ptr Client, resource: ptr Resource, edges: uint32) {.nimcall.}
  getDecorationAbove*: proc(
    client: ptr Client, resource: ptr Resource, id: uint32, surface: ptr Resource
  ) {.nimcall.}
  getDecorationBelow*: proc(
    client: ptr Client, resource: ptr Resource, id: uint32, surface: ptr Resource
  ) {.nimcall.}
  informResizeStart*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  informResizeEnd*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  setCapabilities*:
    proc(client: ptr Client, resource: ptr Resource, caps: uint32) {.nimcall.}
  informMaximized*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  informUnmaximized*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  informFullscreen*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  informNotFullscreen*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  fullscreen*:
    proc(client: ptr Client, resource: ptr Resource, output: ptr Resource) {.nimcall.}
  exitFullscreen*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  setClipBox*: proc(
    client: ptr Client,
    resource: ptr Resource,
    x: int32,
    y: int32,
    width: int32,
    height: int32,
  ) {.nimcall.}
  setContentClipBox*: proc(
    client: ptr Client,
    resource: ptr Resource,
    x: int32,
    y: int32,
    width: int32,
    height: int32,
  ) {.nimcall.}
  setDimensionBounds*: proc(
    client: ptr Client, resource: ptr Resource, maxWidth: int32, maxHeight: int32
  ) {.nimcall.}

proc riverWindowV1SendClosed*(
    resource: ptr Resource
) {.inline, exportc: "river_window_v1_send_closed".} =
  ## Sends an closed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowV1Event_closed.ord)

proc riverWindowV1SendDimensionsHint*(
    resource: ptr Resource,
    minWidth: int32,
    minHeight: int32,
    maxWidth: int32,
    maxHeight: int32,
) {.inline, exportc: "river_window_v1_send_dimensions_hint".} =
  ## Sends an dimensions_hint event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *min_width*: minimum width
  ## * *min_height*: minimum height
  ## * *max_width*: maximum width
  ## * *max_height*: maximum height
  resource.post_event(
    RiverWindowV1Event_dimensions_hint.ord, minWidth, minHeight, maxWidth, maxHeight
  )

proc riverWindowV1SendDimensions*(
    resource: ptr Resource, width: int32, height: int32
) {.inline, exportc: "river_window_v1_send_dimensions".} =
  ## Sends an dimensions event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *width*: window content width
  ## * *height*: window content height
  resource.post_event(RiverWindowV1Event_dimensions.ord, width, height)

proc riverWindowV1SendAppId*(
    resource: ptr Resource, appId: cstring
) {.inline, exportc: "river_window_v1_send_app_id".} =
  ## Sends an app_id event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *app_id*: window application ID
  resource.post_event(RiverWindowV1Event_app_id.ord, appId)

proc riverWindowV1SendTitle*(
    resource: ptr Resource, title: cstring
) {.inline, exportc: "river_window_v1_send_title".} =
  ## Sends an title event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *title*: window title
  resource.post_event(RiverWindowV1Event_title.ord, title)

proc riverWindowV1SendParent*(
    resource: ptr Resource, parent: ptr Resource
) {.inline, exportc: "river_window_v1_send_parent".} =
  ## Sends an parent event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *parent*: parent window, if any
  resource.post_event(RiverWindowV1Event_parent.ord, parent)

proc riverWindowV1SendDecorationHint*(
    resource: ptr Resource, hint: uint32
) {.inline, exportc: "river_window_v1_send_decoration_hint".} =
  ## Sends an decoration_hint event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *hint*: decoration hint
  resource.post_event(RiverWindowV1Event_decoration_hint.ord, hint)

proc riverWindowV1SendPointerMoveRequested*(
    resource: ptr Resource, seat: ptr Resource
) {.inline, exportc: "river_window_v1_send_pointer_move_requested".} =
  ## Sends an pointer_move_requested event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *seat*: requested seat
  resource.post_event(RiverWindowV1Event_pointer_move_requested.ord, seat)

proc riverWindowV1SendPointerResizeRequested*(
    resource: ptr Resource, seat: ptr Resource, edges: uint32
) {.inline, exportc: "river_window_v1_send_pointer_resize_requested".} =
  ## Sends an pointer_resize_requested event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *seat*: requested seat
  ## * *edges*: requested edges
  resource.post_event(RiverWindowV1Event_pointer_resize_requested.ord, seat, edges)

proc riverWindowV1SendShowWindowMenuRequested*(
    resource: ptr Resource, x: int32, y: int32
) {.inline, exportc: "river_window_v1_send_show_window_menu_requested".} =
  ## Sends an show_window_menu_requested event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *x*: x offset from top left corner
  ## * *y*: y offset from top left corner
  resource.post_event(RiverWindowV1Event_show_window_menu_requested.ord, x, y)

proc riverWindowV1SendMaximizeRequested*(
    resource: ptr Resource
) {.inline, exportc: "river_window_v1_send_maximize_requested".} =
  ## Sends an maximize_requested event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowV1Event_maximize_requested.ord)

proc riverWindowV1SendUnmaximizeRequested*(
    resource: ptr Resource
) {.inline, exportc: "river_window_v1_send_unmaximize_requested".} =
  ## Sends an unmaximize_requested event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowV1Event_unmaximize_requested.ord)

proc riverWindowV1SendFullscreenRequested*(
    resource: ptr Resource, output: ptr Resource
) {.inline, exportc: "river_window_v1_send_fullscreen_requested".} =
  ## Sends an fullscreen_requested event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *output*: fullscreen output requested
  resource.post_event(RiverWindowV1Event_fullscreen_requested.ord, output)

proc riverWindowV1SendExitFullscreenRequested*(
    resource: ptr Resource
) {.inline, exportc: "river_window_v1_send_exit_fullscreen_requested".} =
  ## Sends an exit_fullscreen_requested event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowV1Event_exit_fullscreen_requested.ord)

proc riverWindowV1SendMinimizeRequested*(
    resource: ptr Resource
) {.inline, exportc: "river_window_v1_send_minimize_requested".} =
  ## Sends an minimize_requested event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverWindowV1Event_minimize_requested.ord)

proc riverWindowV1SendUnreliablePid*(
    resource: ptr Resource, unreliablePid: int32
) {.inline, exportc: "river_window_v1_send_unreliable_pid".} =
  ## Sends an unreliable_pid event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *unreliable_pid*: unreliable PID
  resource.post_event(RiverWindowV1Event_unreliable_pid.ord, unreliablePid)

proc riverWindowV1SendPresentationHint*(
    resource: ptr Resource, hint: uint32
) {.inline, exportc: "river_window_v1_send_presentation_hint".} =
  ## Sends an presentation_hint event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *hint*: presentation hint
  resource.post_event(RiverWindowV1Event_presentation_hint.ord, hint)

proc riverWindowV1SendIdentifier*(
    resource: ptr Resource, identifier: cstring
) {.inline, exportc: "river_window_v1_send_identifier".} =
  ## Sends an identifier event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *identifier*: unique identifier
  resource.post_event(RiverWindowV1Event_identifier.ord, identifier)

proc riverWindowV1SendCaptureSessions*(
    resource: ptr Resource, count: uint32
) {.inline, exportc: "river_window_v1_send_capture_sessions".} =
  ## Sends an capture_sessions event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  ## * *count*: count of screen capture sessions
  resource.post_event(RiverWindowV1Event_capture_sessions.ord, count)

type RiverDecorationV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  setOffset*:
    proc(client: ptr Client, resource: ptr Resource, x: int32, y: int32) {.nimcall.}
  syncNextCommit*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

type RiverShellSurfaceV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  getNode*: proc(client: ptr Client, resource: ptr Resource, id: uint32) {.nimcall.}
  syncNextCommit*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

type RiverNodeV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  setPosition*:
    proc(client: ptr Client, resource: ptr Resource, x: int32, y: int32) {.nimcall.}
  placeTop*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  placeBottom*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  placeAbove*:
    proc(client: ptr Client, resource: ptr Resource, other: ptr Resource) {.nimcall.}
  placeBelow*:
    proc(client: ptr Client, resource: ptr Resource, other: ptr Resource) {.nimcall.}

type RiverOutputV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  setPresentationMode*:
    proc(client: ptr Client, resource: ptr Resource, mode: uint32) {.nimcall.}

proc riverOutputV1SendRemoved*(
    resource: ptr Resource
) {.inline, exportc: "river_output_v1_send_removed".} =
  ## Sends an removed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverOutputV1Event_removed.ord)

proc riverOutputV1SendOutput*(
    resource: ptr Resource, name: uint32
) {.inline, exportc: "river_output_v1_send_wl_output".} =
  ## Sends an wl_output event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *name*: name of the wl_output global
  resource.post_event(RiverOutputV1Event_wl_output.ord, name)

proc riverOutputV1SendPosition*(
    resource: ptr Resource, x: int32, y: int32
) {.inline, exportc: "river_output_v1_send_position".} =
  ## Sends an position event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *x*: global x coordinate
  ## * *y*: global y coordinate
  resource.post_event(RiverOutputV1Event_position.ord, x, y)

proc riverOutputV1SendDimensions*(
    resource: ptr Resource, width: int32, height: int32
) {.inline, exportc: "river_output_v1_send_dimensions".} =
  ## Sends an dimensions event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *width*: output width
  ## * *height*: output height
  resource.post_event(RiverOutputV1Event_dimensions.ord, width, height)

proc riverOutputV1SendCaptureSessions*(
    resource: ptr Resource, count: uint32
) {.inline, exportc: "river_output_v1_send_capture_sessions".} =
  ## Sends an capture_sessions event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  ## * *count*: count of screen capture sessions
  resource.post_event(RiverOutputV1Event_capture_sessions.ord, count)

type RiverSeatV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  focusWindow*:
    proc(client: ptr Client, resource: ptr Resource, window: ptr Resource) {.nimcall.}
  focusShellSurface*: proc(
    client: ptr Client, resource: ptr Resource, shellSurface: ptr Resource
  ) {.nimcall.}
  clearFocus*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  opStartPointer*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  opEnd*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  getPointerBinding*: proc(
    client: ptr Client,
    resource: ptr Resource,
    id: uint32,
    button: uint32,
    modifiers: uint32,
  ) {.nimcall.}
  setXcursorTheme*: proc(
    client: ptr Client, resource: ptr Resource, name: cstring, size: uint32
  ) {.nimcall.}
  pointerWarp*:
    proc(client: ptr Client, resource: ptr Resource, x: int32, y: int32) {.nimcall.}

proc riverSeatV1SendRemoved*(
    resource: ptr Resource
) {.inline, exportc: "river_seat_v1_send_removed".} =
  ## Sends an removed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverSeatV1Event_removed.ord)

proc riverSeatV1SendSeat*(
    resource: ptr Resource, name: uint32
) {.inline, exportc: "river_seat_v1_send_wl_seat".} =
  ## Sends an wl_seat event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *name*: name of the wl_seat global
  resource.post_event(RiverSeatV1Event_wl_seat.ord, name)

proc riverSeatV1SendPointerEnter*(
    resource: ptr Resource, window: ptr Resource
) {.inline, exportc: "river_seat_v1_send_pointer_enter".} =
  ## Sends an pointer_enter event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *window*: window entered
  resource.post_event(RiverSeatV1Event_pointer_enter.ord, window)

proc riverSeatV1SendPointerLeave*(
    resource: ptr Resource
) {.inline, exportc: "river_seat_v1_send_pointer_leave".} =
  ## Sends an pointer_leave event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverSeatV1Event_pointer_leave.ord)

proc riverSeatV1SendWindowInteraction*(
    resource: ptr Resource, window: ptr Resource
) {.inline, exportc: "river_seat_v1_send_window_interaction".} =
  ## Sends an window_interaction event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *window*: window interacted with
  resource.post_event(RiverSeatV1Event_window_interaction.ord, window)

proc riverSeatV1SendShellSurfaceInteraction*(
    resource: ptr Resource, shellSurface: ptr Resource
) {.inline, exportc: "river_seat_v1_send_shell_surface_interaction".} =
  ## Sends an shell_surface_interaction event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *shell_surface*: shell surface interacted with
  resource.post_event(RiverSeatV1Event_shell_surface_interaction.ord, shellSurface)

proc riverSeatV1SendOpDelta*(
    resource: ptr Resource, dx: int32, dy: int32
) {.inline, exportc: "river_seat_v1_send_op_delta".} =
  ## Sends an op_delta event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *dx*: total change in x
  ## * *dy*: total change in y
  resource.post_event(RiverSeatV1Event_op_delta.ord, dx, dy)

proc riverSeatV1SendOpRelease*(
    resource: ptr Resource
) {.inline, exportc: "river_seat_v1_send_op_release".} =
  ## Sends an op_release event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverSeatV1Event_op_release.ord)

proc riverSeatV1SendPointerPosition*(
    resource: ptr Resource, x: int32, y: int32
) {.inline, exportc: "river_seat_v1_send_pointer_position".} =
  ## Sends an pointer_position event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *x*: global x coordinate
  ## * *y*: global y coordinate
  resource.post_event(RiverSeatV1Event_pointer_position.ord, x, y)

type RiverPointerBindingV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  enable*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  disable*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc riverPointerBindingV1SendPressed*(
    resource: ptr Resource
) {.inline, exportc: "river_pointer_binding_v1_send_pressed".} =
  ## Sends an pressed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverPointerBindingV1Event_pressed.ord)

proc riverPointerBindingV1SendReleased*(
    resource: ptr Resource
) {.inline, exportc: "river_pointer_binding_v1_send_released".} =
  ## Sends an released event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverPointerBindingV1Event_released.ord)
