# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/client
import wayland/native/common
import code
export code

## The wlr_screencopy_unstable_v1 CLIENT protocol
## ##############################################
##
## Interfaces
## ==========
##
## * zwlr_screencopy_manager_v1
## * zwlr_screencopy_frame_v1
##
## Copyright
## =========
##
## Copyright © 2018 Simon Ser
## Copyright © 2019 Andri Yngvason
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice (including the next
## paragraph) shall be included in all copies or substantial portions of the
## Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.
##

proc setUserData*(
    zwlrScreencopyManagerV1: ptr ZwlrScreencopyManagerV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](zwlrScreencopyManagerV1).set_user_data(user_data)

proc getUserData*(
    zwlrScreencopyManagerV1: ptr ZwlrScreencopyManagerV1
): pointer {.inline.} =
  cast[ptr Proxy](zwlrScreencopyManagerV1).get_user_data()

proc getVersion*(
    zwlrScreencopyManagerV1: ptr ZwlrScreencopyManagerV1
): uint32 {.inline.} =
  cast[ptr Proxy](zwlrScreencopyManagerV1).get_version()

proc captureOutput*(
    zwlrScreencopyManagerV1: ptr ZwlrScreencopyManagerV1,
    overlayCursor: int32,
    output: ptr Output,
): ptr ZwlrScreencopyFrameV1 {.inline.} =
  ## capture an output
  ##
  ## Capture the next frame of an entire output.
  ##
  cast[ptr ZwlrScreencopyFrameV1](cast[ptr Proxy](zwlrScreencopyManagerV1).marshal_flags(
    ZwlrScreencopyManagerV1Request_capture_output.ord,
    addr zwlr_screencopy_frame_v1_interface,
    cast[ptr Proxy](zwlrScreencopyManagerV1).get_version(),
    0,
    nil,
    overlayCursor,
    output,
  ))

proc captureOutputRegion*(
    zwlrScreencopyManagerV1: ptr ZwlrScreencopyManagerV1,
    overlayCursor: int32,
    output: ptr Output,
    x: int32,
    y: int32,
    width: int32,
    height: int32,
): ptr ZwlrScreencopyFrameV1 {.inline.} =
  ## capture an output's region
  ##
  ## Capture the next frame of an output's region.
  ##
  ## The region is given in output logical coordinates, see
  ## xdg_output.logical_size. The region will be clipped to the output's
  ## extents.
  ##
  cast[ptr ZwlrScreencopyFrameV1](cast[ptr Proxy](zwlrScreencopyManagerV1).marshal_flags(
    ZwlrScreencopyManagerV1Request_capture_output_region.ord,
    addr zwlr_screencopy_frame_v1_interface,
    cast[ptr Proxy](zwlrScreencopyManagerV1).get_version(),
    0,
    nil,
    overlayCursor,
    output,
    x,
    y,
    width,
    height,
  ))

proc destroy*(zwlrScreencopyManagerV1: ptr ZwlrScreencopyManagerV1) {.inline.} =
  ## destroy the manager
  ##
  ## All objects created by the manager will still remain valid, until their
  ## appropriate destroy request has been called.
  ##
  cast[ptr Proxy](zwlrScreencopyManagerV1).marshal_flags(
    ZwlrScreencopyManagerV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](zwlrScreencopyManagerV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

type ZwlrScreencopyFrameV1Listener* = object
  buffer*: proc(
    data: pointer,
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1,
    format: uint32,
    width: uint32,
    height: uint32,
    stride: uint32,
  ) {.nimcall.}
  flags*: proc(
    data: pointer, zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1, flags: uint32
  ) {.nimcall.}
  ready*: proc(
    data: pointer,
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1,
    tvSecHi: uint32,
    tvSecLo: uint32,
    tvNsec: uint32,
  ) {.nimcall.}
  failed*:
    proc(data: pointer, zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1) {.nimcall.}
  damage*: proc(
    data: pointer,
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1,
    x: uint32,
    y: uint32,
    width: uint32,
    height: uint32,
  ) {.nimcall.}
  linuxDmabuf*: proc(
    data: pointer,
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1,
    format: uint32,
    width: uint32,
    height: uint32,
  ) {.nimcall.}
  bufferDone*:
    proc(data: pointer, zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1) {.nimcall.}

proc addListener*(
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1,
    listener: ptr ZwlrScreencopyFrameV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](zwlrScreencopyFrameV1).add_listener(listener, data)

proc setUserData*(
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](zwlrScreencopyFrameV1).set_user_data(user_data)

proc getUserData*(
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1
): pointer {.inline.} =
  cast[ptr Proxy](zwlrScreencopyFrameV1).get_user_data()

proc getVersion*(zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1): uint32 {.inline.} =
  cast[ptr Proxy](zwlrScreencopyFrameV1).get_version()

proc copy*(
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1, buffer: ptr Buffer
) {.inline.} =
  ## copy the frame
  ##
  ## Copy the frame to the supplied buffer. The buffer must have a the
  ## correct size, see zwlr_screencopy_frame_v1.buffer and
  ## zwlr_screencopy_frame_v1.linux_dmabuf. The buffer needs to have a
  ## supported format.
  ##
  ## If the frame is successfully copied, a "flags" and a "ready" events are
  ## sent. Otherwise, a "failed" event is sent.
  ##
  cast[ptr Proxy](zwlrScreencopyFrameV1).marshal_flags(
    ZwlrScreencopyFrameV1Request_copy.ord,
    nil,
    cast[ptr Proxy](zwlrScreencopyFrameV1).get_version(),
    0,
    buffer,
  )

proc destroy*(zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1) {.inline.} =
  ## delete this object, used or not
  ##
  ## Destroys the frame. This request can be sent at any time by the client.
  ##
  cast[ptr Proxy](zwlrScreencopyFrameV1).marshal_flags(
    ZwlrScreencopyFrameV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](zwlrScreencopyFrameV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc copyWithDamage*(
    zwlrScreencopyFrameV1: ptr ZwlrScreencopyFrameV1, buffer: ptr Buffer
) {.inline.} =
  ## copy the frame when it's damaged
  ##
  ## Same as copy, except it waits until there is damage to copy.
  ##
  cast[ptr Proxy](zwlrScreencopyFrameV1).marshal_flags(
    ZwlrScreencopyFrameV1Request_copy_with_damage.ord,
    nil,
    cast[ptr Proxy](zwlrScreencopyFrameV1).get_version(),
    0,
    buffer,
  )
