# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var wlrScreencopyUnstableV1_types: array[16, ptr Interface]
type ZwlrScreencopyFrameV1* = object
type ZwlrScreencopyManagerV1* = object

let
  zwlr_screencopy_manager_v1_requests {.exportc.} = [
    Message(
      name: "capture_output",
      signature: "nio",
      types: addr wlr_screencopy_unstable_v1_types[4],
    ),
    Message(
      name: "capture_output_region",
      signature: "nioiiii",
      types: addr wlr_screencopy_unstable_v1_types[7],
    ),
    Message(
      name: "destroy", signature: "", types: addr wlr_screencopy_unstable_v1_types[0]
    ),
  ]

  zwlr_screencopy_manager_v1_interface* {.exportc.} = Interface(
    name: "zwlr_screencopy_manager_v1",
    version: 3,
    method_count: 3,
    methods: addr zwlr_screencopy_manager_v1_requests[0],
  )

  zwlr_screencopy_frame_v1_requests {.exportc.} = [
    Message(
      name: "copy", signature: "o", types: addr wlr_screencopy_unstable_v1_types[14]
    ),
    Message(
      name: "destroy", signature: "", types: addr wlr_screencopy_unstable_v1_types[0]
    ),
    Message(
      name: "copy_with_damage",
      signature: "2o",
      types: addr wlr_screencopy_unstable_v1_types[15],
    ),
  ]

  zwlr_screencopy_frame_v1_events {.exportc.} = [
    Message(
      name: "buffer", signature: "uuuu", types: addr wlr_screencopy_unstable_v1_types[0]
    ),
    Message(
      name: "flags", signature: "u", types: addr wlr_screencopy_unstable_v1_types[0]
    ),
    Message(
      name: "ready", signature: "uuu", types: addr wlr_screencopy_unstable_v1_types[0]
    ),
    Message(
      name: "failed", signature: "", types: addr wlr_screencopy_unstable_v1_types[0]
    ),
    Message(
      name: "damage",
      signature: "2uuuu",
      types: addr wlr_screencopy_unstable_v1_types[0],
    ),
    Message(
      name: "linux_dmabuf",
      signature: "3uuu",
      types: addr wlr_screencopy_unstable_v1_types[0],
    ),
    Message(
      name: "buffer_done",
      signature: "3",
      types: addr wlr_screencopy_unstable_v1_types[0],
    ),
  ]

  zwlr_screencopy_frame_v1_interface* {.exportc.} = Interface(
    name: "zwlr_screencopy_frame_v1",
    version: 3,
    method_count: 3,
    methods: addr zwlr_screencopy_frame_v1_requests[0],
    event_count: 7,
    events: addr zwlr_screencopy_frame_v1_events[0],
  )

type ZwlrScreencopyFrameV1Error* {.size: sizeof(uint32).} = enum
  error_already_used = 0
  error_invalid_buffer = 1

func since*(e: ZwlrScreencopyFrameV1Error): int =
  case e
  of error_already_used: 1
  of error_invalid_buffer: 1
proc isValid*(e: ZwlrScreencopyFrameV1Error, version: int): bool =
  version >= e.since

type ZwlrScreencopyFrameV1Flags* {.size: sizeof(uint32).} = enum
  flags_y_invert = 1

func since*(e: ZwlrScreencopyFrameV1Flags): int =
  case e
  of flags_y_invert: 1
proc isValid*(e: ZwlrScreencopyFrameV1Flags, version: int): bool =
  version >= e.since

type ZwlrScreencopyManagerV1Request* {.size: sizeof(uint32).} = enum
  ZwlrScreencopyManagerV1Request_capture_output
  ZwlrScreencopyManagerV1Request_capture_output_region
  ZwlrScreencopyManagerV1Request_destroy

proc since*(e: ZwlrScreencopyManagerV1Request): int =
  case e
  of ZwlrScreencopyManagerV1Request_capture_output: 1
  of ZwlrScreencopyManagerV1Request_capture_output_region: 1
  of ZwlrScreencopyManagerV1Request_destroy: 1

type ZwlrScreencopyFrameV1Event* {.size: sizeof(uint32).} = enum
  ZwlrScreencopyFrameV1Event_buffer
  ZwlrScreencopyFrameV1Event_flags
  ZwlrScreencopyFrameV1Event_ready
  ZwlrScreencopyFrameV1Event_failed
  ZwlrScreencopyFrameV1Event_damage
  ZwlrScreencopyFrameV1Event_linux_dmabuf
  ZwlrScreencopyFrameV1Event_buffer_done

proc since*(e: ZwlrScreencopyFrameV1Event): int =
  case e
  of ZwlrScreencopyFrameV1Event_buffer: 1
  of ZwlrScreencopyFrameV1Event_flags: 1
  of ZwlrScreencopyFrameV1Event_ready: 1
  of ZwlrScreencopyFrameV1Event_failed: 1
  of ZwlrScreencopyFrameV1Event_damage: 2
  of ZwlrScreencopyFrameV1Event_linux_dmabuf: 3
  of ZwlrScreencopyFrameV1Event_buffer_done: 3

type ZwlrScreencopyFrameV1Request* {.size: sizeof(uint32).} = enum
  ZwlrScreencopyFrameV1Request_copy
  ZwlrScreencopyFrameV1Request_destroy
  ZwlrScreencopyFrameV1Request_copy_with_damage

proc since*(e: ZwlrScreencopyFrameV1Request): int =
  case e
  of ZwlrScreencopyFrameV1Request_copy: 1
  of ZwlrScreencopyFrameV1Request_destroy: 1
  of ZwlrScreencopyFrameV1Request_copy_with_damage: 2

wlrScreencopyUnstableV1_types = [
  nil,
  nil,
  nil,
  nil,
  addr zwlr_screencopy_frame_v1_interface,
  nil,
  addr wl_output_interface,
  addr zwlr_screencopy_frame_v1_interface,
  nil,
  addr wl_output_interface,
  nil,
  nil,
  nil,
  nil,
  addr wl_buffer_interface,
  addr wl_buffer_interface,
]
