# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/server
import wayland/native/common
import code
export code

## The wlr_screencopy_unstable_v1 SERVER protocol
## ##############################################
##
## Interfaces
## ==========
##
## * zwlr_screencopy_manager_v1
## * zwlr_screencopy_frame_v1
##
## Copyright
## =========
##
## Copyright © 2018 Simon Ser
## Copyright © 2019 Andri Yngvason
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice (including the next
## paragraph) shall be included in all copies or substantial portions of the
## Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.
##

type ZwlrScreencopyManagerV1Interface* = object
  captureOutput*: proc(
    client: ptr Client,
    resource: ptr Resource,
    frame: uint32,
    overlayCursor: int32,
    output: ptr Resource,
  ) {.nimcall.}
  captureOutputRegion*: proc(
    client: ptr Client,
    resource: ptr Resource,
    frame: uint32,
    overlayCursor: int32,
    output: ptr Resource,
    x: int32,
    y: int32,
    width: int32,
    height: int32,
  ) {.nimcall.}
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

type ZwlrScreencopyFrameV1Interface* = object
  copy*:
    proc(client: ptr Client, resource: ptr Resource, buffer: ptr Resource) {.nimcall.}
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  copyWithDamage*:
    proc(client: ptr Client, resource: ptr Resource, buffer: ptr Resource) {.nimcall.}

proc zwlrScreencopyFrameV1SendBuffer*(
    resource: ptr Resource,
    format: uint32,
    width: uint32,
    height: uint32,
    stride: uint32,
) {.inline, exportc: "zwlr_screencopy_frame_v1_send_buffer".} =
  ## Sends an buffer event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  ## * *format*: buffer format
  ## * *width*: buffer width
  ## * *height*: buffer height
  ## * *stride*: buffer stride
  resource.post_event(
    ZwlrScreencopyFrameV1Event_buffer.ord, format, width, height, stride
  )

proc zwlrScreencopyFrameV1SendFlags*(
    resource: ptr Resource, flags: uint32
) {.inline, exportc: "zwlr_screencopy_frame_v1_send_flags".} =
  ## Sends an flags event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  ## * *flags*: frame flags
  resource.post_event(ZwlrScreencopyFrameV1Event_flags.ord, flags)

proc zwlrScreencopyFrameV1SendReady*(
    resource: ptr Resource, tvSecHi: uint32, tvSecLo: uint32, tvNsec: uint32
) {.inline, exportc: "zwlr_screencopy_frame_v1_send_ready".} =
  ## Sends an ready event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  ## * *tv_sec_hi*: high 32 bits of the seconds part of the timestamp
  ## * *tv_sec_lo*: low 32 bits of the seconds part of the timestamp
  ## * *tv_nsec*: nanoseconds part of the timestamp
  resource.post_event(ZwlrScreencopyFrameV1Event_ready.ord, tvSecHi, tvSecLo, tvNsec)

proc zwlrScreencopyFrameV1SendFailed*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_screencopy_frame_v1_send_failed".} =
  ## Sends an failed event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrScreencopyFrameV1Event_failed.ord)

proc zwlrScreencopyFrameV1SendDamage*(
    resource: ptr Resource, x: uint32, y: uint32, width: uint32, height: uint32
) {.inline, exportc: "zwlr_screencopy_frame_v1_send_damage".} =
  ## Sends an damage event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  ## * *x*: damaged x coordinates
  ## * *y*: damaged y coordinates
  ## * *width*: current width
  ## * *height*: current height
  resource.post_event(ZwlrScreencopyFrameV1Event_damage.ord, x, y, width, height)

proc zwlrScreencopyFrameV1SendLinuxDmabuf*(
    resource: ptr Resource, format: uint32, width: uint32, height: uint32
) {.inline, exportc: "zwlr_screencopy_frame_v1_send_linux_dmabuf".} =
  ## Sends an linux_dmabuf event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  ## * *format*: fourcc pixel format
  ## * *width*: buffer width
  ## * *height*: buffer height
  resource.post_event(
    ZwlrScreencopyFrameV1Event_linux_dmabuf.ord, format, width, height
  )

proc zwlrScreencopyFrameV1SendBufferDone*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_screencopy_frame_v1_send_buffer_done".} =
  ## Sends an buffer_done event to the client owning the resource.
  ##
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrScreencopyFrameV1Event_buffer_done.ord)
